---
# General Information --------------------------------------------------------
title:    "Duomenų analizė"
author:   "VytautasCepas"
date:     "`r Sys.Date()`" # Automatic date
# Document Format and Appearance ---------------------------------------------
output:
  bookdown::html_document2: # Enables automatic numbering of figures & tables
    highlight:       tango # default tango kate monochrome espresso ...
    code_folding:    none     # none show hide
    code_download:   yes      # yes no
    number_sections: yes      # Automatic numbering of sections: yes no
    toc:         yes          # Table of contents (toc): yes no
    toc_float:   yes          # yes no
    toc_depth:   2            # 1 2 3 4 5
    fig_caption: yes          # yes no
    theme:       cerulean      # cerulean journal flatly readable paper sandstone ...
    df_print:    default      # paged kable tibble default
---

```{r setup, error=FALSE, warning=FALSE, message=FALSE, results='hide'}
# Packages ------------------------------------------------------------------

library(conflicted)    # Get a warning/error if several functions with the same name exist.
library(magrittr)      # Operator %>% and additional pipe-friendly functions.
library(tidyverse)     # The main "tidyverse" packages.

library(fs)            # Manage files and directories.

library(data.table)    # Function `fread()` to read data from text files.
library(readxl)        # Read Excel data.
library(writexl)       # Write data to Excel files.
library(openxlsx)      # Write data to Excel files.

library(ggpubr)        # Statistical plots and utilities for ggplot2.
#library(ggstatsplot)   # Statistical plots based on ggplot2.
library(ggmosaic)      # Mosaic plot (ggplot2).
library(qqplotr)       # Quantile comparison diagrams (QQ plots).
library(ggtext)        # Improved Text Rendering Support for ggplot2.
library(ggrepel)       # Labels for ggplot2 that do not overlap.
library(patchwork)     # Join several ggplot2 plots into single figure.
library(gghighlight)   # Highlight Lines and Points in ggplot2.
library(latex2exp)     # LaTeX-based equations in plots.
library(officer)       # Create and manipulate PowerPoint, Word, etc. documents.
library(rvg)           # To save editable plots in PowerPoint.

library(broom)         # Convert results of statistical analysis to data frames.
library(rstatix)       # Pipe-friendly basic statistical tests.
library(rcompanion)    # Statistical analysis.
library(RVAideMemoire) # Statistical analysis.
library(PMCMRplus)     # Non-parametric statistical tests.
library(vcd)           # Analysis of categorical data.
library(fitdistrplus)  # Fit parametric distributions.
library(mlr)           # Machine learning in R.
library(mlr3)          # Machine learning in R (new generation).
library(factoextra)    # Extract and visualize the results of multivariate data analyses.
#library(userfriendlyscience) # Statistical analysis.

library(pander)        # Function `pander()` to report results of statistical analysis.
library(knitr)         # Function `kable()` to convert data frames into tables for reports.
library(DT)            # Interactive tables for HTML documents (DataTables).
library(gt)            # Easily Create Presentation-Ready Display Tables.
library(flextable)     # Functions for Tabular Reporting.


# Settings ------------------------------------------------------------------

Sys.setlocale(locale = "Lithuanian")

# Chunk options
knitr::opts_chunk$set(
  echo       = TRUE,    # Should blocks with program code be shown in knitted documents?
  eval       = TRUE,    # Should program code be evaluated?
  fig.height = 3,       # Default height for plots.
  fig.width  = 5,       # Default width for plots.
  fig.align  = "center" # Default alignment for plots in knitted documents.
)

#opts-r-numbers
#opts-desctools
#opts-pander

ggplot2::theme_set(ggplot2::theme_bw()) # Default ggplot2 theme

conflicted::conflict_prefer("filter", "dplyr")
conflicted::conflict_prefer("lag",    "dplyr")

set.seed(20210125) # Initial condition for random processes.
```

# Duoneų įkėlimas
```{r}
data("wdbc", package = "mclust")
```

# Skaitinė suvestinė
## Suvestini iš vidurkių
```{r}
duomenu_vidurkiai <- wdbc %>% 
  summarise(
    across(
      ends_with("mean"), mean,))
```
### Lentelės atvaizdavimas
```{r lent-1}
lent <- head(duomenu_vidurkiai)
knitr::kable(
  lent,
  caption = "Kelios duomenų eilutės iš suvestinė - duomenu_vidurkiai.  "
)
```
## Suvestinė standartinio nuoktrypio
```{r}
duomenu_sd <- wdbc %>% 
  summarise(
    across(
      ends_with("sd"), sd = sd,))
```
### Lentelės atvaizdavimas
```{r lent-2}
lent <- head(duomenu_sd)
knitr::kable(
  lent,
  caption = "Kelios duomenų eilutės iš suvestinė - duomenu_sd.  "
)
```
